### ISSUE TITLE
FTM2 Crashes when starting to control BOINC

### ISSUE THREAD

**Issue by HeyMerlin** [makeasnek/FindTheMag2#10]
Error message:
```
Press enter key to start controlling BOINC. Press Ctrl+C to quit

Starting control of BOINC...
Traceback (most recent call last):
  File "/home/piadm/FTM2/FindTheMag2/main.py", line 2620, in <module>
    loop.run_until_complete(prefs_check(rpc_client))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/piadm/FTM2/FindTheMag2/main.py", line 1518, in prefs_check
    max_gb=int(float(parsed.get('disk_max_used_gb',0)))
AttributeError: 'bool' object has no attribute 'get'
```

- Running on a Raspberry Pi: 64bit OS
- BOINC installed and running
- No Gridcoin Wallet installed
- Pulled latest FTM2 that included the security fix
- Same install procedure works on another RPi (installed that one first and followed the same directions to install this one)

Global prefs file
```
<global_preferences>

    <host_specific/>
    <source_project>http://bam.boincstats.com/</source_project>
    <mod_time>1668647832</mod_time>
    <run_if_user_active>1</run_if_user_active>
    <run_gpu_if_user_active>1</run_gpu_if_user_active>
    <suspend_if_no_recent_input>0</suspend_if_no_recent_input>
    <cpu_scheduling_period_minutes>60</cpu_scheduling_period_minutes>
    <idle_time_to_run>3</idle_time_to_run>
    <leave_apps_in_memory/>
    <work_buf_min_days>0.1</work_buf_min_days>
    <work_buf_additional_days>1</work_buf_additional_days>
    <max_cpus>20</max_cpus>
    <max_ncpus_pct>100</max_ncpus_pct>
    <suspend_cpu_usage>0</suspend_cpu_usage>
    <cpu_usage_limit>100</cpu_usage_limit>
    <disk_interval>60</disk_interval>
    <disk_max_used_gb>100</disk_max_used_gb>
    <disk_max_used_pct>50</disk_max_used_pct>
    <disk_min_free_gb>1</disk_min_free_gb>
    <vm_max_used_pct>75</vm_max_used_pct>
    <ram_max_used_busy_pct>60</ram_max_used_busy_pct>
    <ram_max_used_idle_pct>90</ram_max_used_idle_pct>
    <max_bytes_sec_down>0</max_bytes_sec_down>
    <max_bytes_sec_up>0</max_bytes_sec_up>
    <hangup_if_dialed/>
    <start_hour>0</start_hour>
    <end_hour>0</end_hour>
    <net_start_hour>0</net_start_hour>
    <net_end_hour>0</net_end_hour>
  </global_preferences>
```

- Setting logging to DEBUG gives no additional information.

What I can't tell is if this is due to FTM not being able to talk to the boinc client or not.
FTM cannot read the gui_rpc_auth.cfg, but this is the same on both RPis

Let me know if there is any further information I can provide.

**Comment by makeasnek** [comment]
Thank you for the bug report! Can you please replace your main.py file with this one? It will output "TESTINGXXY" at some point, I need that output to figure out what's going on. It will also place it in the log file in case it disappears from the screen too quickly. You can e-mail the log file to makeasnek{at}gmail.com.
[main.py.zip](https://github.com/makeasnek/FindTheMag2/files/11184643/main.py.zip)

**Comment by makeasnek** [comment]
Also how do you know "FTM cannot read the gui_rpc_auth.cfg". FTM should be able to read this in order to connect to the boinc client.

**Comment by HeyMerlin** [comment]
Regarding gui_rpc_auth.cfg... two reasons:
1. permissions and ownership is set such that only the boinc user can access the file.
2. I set the log to DEBUG in config.py and received the following
```
DEBUG:root:Error reading boinc RPC file at /var/lib/boinc-client/gui_rpc_auth.cfg: [Errno 13] Permission denied: '/var/lib/boinc-client/gui_rpc_auth.cfg'
```

So looking at my other RPi (RPi1), the permissions on that file are set the same way and yet FTM2 does appear to talk to the local boinc client...
The BOINC event log:
```
Sat  8 Apr 21:22:18 2023 | TN-Grid Platform | work fetch suspended by user
Sat  8 Apr 21:22:18 2023 | Universe@Home | work fetch suspended by user
Sat  8 Apr 21:22:18 2023 | Amicable Numbers | work fetch resumed by user
Sat  8 Apr 21:22:18 2023 | Amicable Numbers | update requested by user
Sat  8 Apr 21:22:19 2023 | Amicable Numbers | Sending scheduler request: Requested by user.
Sat  8 Apr 21:22:19 2023 | Amicable Numbers | Not requesting tasks: don't need (job cache full)
Sat  8 Apr 21:22:21 2023 | Amicable Numbers | Scheduler request completed
Sat  8 Apr 21:22:21 2023 | Amicable Numbers | Project requested delay of 7 seconds
Sat  8 Apr 21:22:34 2023 | Einstein@Home | work fetch suspended by user
Sat  8 Apr 21:22:34 2023 | Rosetta@home | work fetch suspended by user
Sat  8 Apr 21:22:34 2023 | World Community Grid | work fetch suspended by user
Sat  8 Apr 21:22:34 2023 | yoyo@home | work fetch suspended by user
Sat  8 Apr 21:22:34 2023 | Asteroids@home | work fetch suspended by user
Sat  8 Apr 21:22:34 2023 | Amicable Numbers | work fetch suspended by user
```
and the FTM2 log from RPi1 (log setting at INFO on this RPi)
```
INFO:root:Highest priority project is HTTPS://GENE.DISI.UNITN.IT/TEST/
INFO:root:Waiting for any xfers to complete...
INFO:root:Allowing new tasks and updating https://gene.disi.unitn.it/test/
INFO:root:Waiting for any xfers to complete...
INFO:root:Allowing new tasks and updating https://sech.me/boinc/Amicable/
```
looking at the above, FTM allows updates for the Amicable numbers and the change can be seen in the BOINC event log.

I figured since setting permissions for this file was not mentioned in the instructions it was not needed... similar to when running `boinccmd` on the command line, it does not have access to the file either (as it is running as my logged-in user and not the 'boinc' user). However, I'm guessing here and will defer to your expertise.

I'll test with the testing main.py and send you the results. Thanks for looking at this so quickly.

**Comment by makeasnek** [comment]
Do you get this error on both Rpis or just the one that's having trouble connecting? `DEBUG:root:Error reading boinc RPC file at /var/lib/boinc-client/gui_rpc_auth.cfg: [Errno 13] Permission denied: '/var/lib/boinc-client/gui_rpc_auth.cfg'`

**Comment by makeasnek** [comment]
Thank you for the detailed log entries this is quite useful

**Comment by makeasnek** [comment]
Also, I don't need the usernames/passwords, but it would be helpful to know from both your pis if `gui_rpc_auth.cfg` has a username/password specified or not. I have a note in the comments in the code that in Linux this file doesn't actually need to be read by FTM but that may not actually be the case if the password isn't the default hence why I ask

**Comment by HeyMerlin** [comment]
Here is the output using the testing main.py:
```
Starting control of BOINC...
TESTINGXXY: <Element 'unauthorized' at 0x7f963ffd10>
Traceback (most recent call last):
  File "/home/piadm/FTM2/FindTheMag2/main.py", line 2622, in <module>
    loop.run_until_complete(prefs_check(rpc_client))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/piadm/FTM2/FindTheMag2/main.py", line 1520, in prefs_check
    max_gb=int(float(parsed.get('disk_max_used_gb',0)))
AttributeError: 'bool' object has no attribute 'get'
```
Let me know if you want me to email the whole log file.


RPi1: works fine without issues and is the first Pi I set up. I'll switch the log from INFO to DEBUG and see if I get the perms error on gui_rpc_auth.cfg.
RPi2: this is the pi that is crashing and shows the perms issue when accessing gui_rpc_auth.cfg (I have log set to DEBUG)

Regarding your latest message about the passwords... both Pis have a password configured as I access them using the boinc manager from my Mac. The Pis run headless.

**Comment by HeyMerlin** [comment]
Element unauthorized.... so it is failing to talk to the client? I was sure I have both RPis set up and configured identically but maybe I have missed something.

**Comment by makeasnek** [comment]
Yes you are exactly right, it's failing to talk to the client (which is why it has trouble parsing what it _expects_ to be command output but is actually just an error). But it should avoid and/or catch this more gracefully. I'll look into this further.

**Comment by makeasnek** [comment]
Can you test something for me on the rpi where FTM is crashing, in your config.py, set the boinc_password variable to whatever is shown in your `gui_rpc_auth.cfg`? 

It should look like this:
`boinc_password='my_password'`

Does that prevent it from crashing? Either way, FTM should alert the user if it can't connect instead of just blanket crashing.

Also I wanted to double-check that you haven't configured BOINC's rpc to use a non-standard port, the default is 31416. If it has a non-standard port, be sure to set that in config.py as well.

**Comment by makeasnek** [comment]
Actually I know the port is correct, otherwise it wouldn't get the unauthorized response, you can ignore that part of the request. Still want to test the password theory though

**Comment by HeyMerlin** [comment]
I think I found it... and yes it seems to be related to accessing `gui_rpc_auth.cfg`. I have reproduced the error on RPi1 by changing the group ownership of that file...

RPi1 Before when it worked:
```
$ ls -la /etc/boinc-client/
total 36
drwxr-xr-x   2 root  root     4096 Nov 10 21:51 .
drwxr-xr-x 121 root  root    12288 Apr  8 08:45 ..
-rw-rw-r--   1 boinc lpadmin   506 Nov 10 21:51 cc_config.xml
-rw-r--r--   1 boinc boinc      31 Feb  3  2021 config.properties
-rw-rw-rw-   1 piadm lpadmin   298 Apr  8 21:48 global_prefs_override.xml
-rw-r-----   1 boinc lpadmin    12 Oct 27 11:40 gui_rpc_auth.cfg
-rw-r--r--   1 boinc lpadmin   309 Nov  9 19:26 remote_hosts.cfg
```
I don't know why/how the group is set to lpadmin... on my other RPis it is set to `boinc` so I changed it to test:
`$ sudo chgrp boinc /etc/boinc-client/gui_rpc_auth.cfg`
```
$ ls -la /etc/boinc-client/
total 36
drwxr-xr-x   2 root  root     4096 Nov 10 21:51 .
drwxr-xr-x 121 root  root    12288 Apr  8 08:45 ..
-rw-rw-r--   1 boinc lpadmin   506 Nov 10 21:51 cc_config.xml
-rw-r--r--   1 boinc boinc      31 Feb  3  2021 config.properties
-rw-rw-rw-   1 piadm lpadmin   298 Apr  8 21:53 global_prefs_override.xml
-rw-r-----   1 boinc boinc      12 Oct 27 11:40 gui_rpc_auth.cfg
-rw-r--r--   1 boinc lpadmin   309 Nov  9 19:26 remote_hosts.cfg
```
And now RPi1 crashes with the same error.

So I need to set permissions correctly on `gui_rpc_auth.cfg` and I don't want to make it world readable. Going to try changing the group to the normal user I log in with and run FTM and see if that fixes it.

Of course this still leaves the issue you have identified in that FTM should fail more gracefully in this situation.

Will report shortly...

**Comment by makeasnek** [comment]
"Going to try changing the group to the normal user I log in with and run FTM and see if that fixes it." <-- I think the consequence of this will be that boinc itself can no longer access it

**Comment by makeasnek** [comment]
I think instead what you may want to do is add yourself to the BOINC users group so you (and ftm) can read the file:
`sudo usermod -aG boinc your_username_here`

**Comment by HeyMerlin** [comment]
Okay here is the results of testing with setting the permissions...
First the directory perms that I now have set
```
$ ls -la /etc/boinc-client/
total 36
drwxr-xr-x   2 root  root   4096 Nov 10 21:51 .
drwxr-xr-x 121 root  root  12288 Apr  8 08:45 ..
-rw-rw-r--   1 boinc boinc   506 Nov 10 21:51 cc_config.xml
-rw-r--r--   1 boinc boinc    31 Feb  3  2021 config.properties
-rw-rw-r--   1 piadm boinc   298 Apr  8 22:08 global_prefs_override.xml
-rw-r-----   1 boinc piadm    12 Oct 27 11:40 gui_rpc_auth.cfg
-rw-r--r--   1 boinc boinc   309 Nov  9 19:26 remote_hosts.cfg
```
The `boinc` user is what runs the boinc client.
The `piadm` is my normal user that I run FTM in.
For `gui_rpc_auth.cfg`, leaving the owner as `boinc` still allows my remote boinc manager to access boinc on that RPi. Setting the group to `piadm` (with only read access) stop FTM from crashing and it no longer reports the access error for this file in the log (at the DEBUG level).

So this error/issue was due to a misconfiguration of the ownership/permissions on the `gui_rpc_auth.cfg` file on my RPi2.
On RPi1, somehow having the group owner `lpadmin` allowed FTM to access the file... I'm not going to dig into this one.

Also, an observation: One more permissions point I ran into... regarding the file `global_prefs_override.xml` (which is not part of this issue):
I found that I could not get FTM to work (have access) if I did any of the following:
- made the file world read/write (rw-rw-rw) but owned by boinc:boinc
- changed the group ownership to piadm (the users running FTM), so boinc:piadm
The only way I can get FTM to not complain is if I change the ownership of the file to piadm... although I could leave the group ownership as boinc. I'm not sure if this is due to how you are testing for access or not. I would have thought that so long as the file is world read/write that FTM would be fine. With world read/write the piadm user had no problem writing to the file (I tested this my manually editing the file).

**Comment by HeyMerlin** [comment]
Also just confirmed that with the file perms set as mentioned above that RPi1 works and successfully communicates with the boinc client.

**Comment by HeyMerlin** [comment]
Just configured RPi2 with the permissions and ownership shown above and it now works without crashing, and it is successfully talking to the boinc client.

You may want to update the Readme to include information regarding setting the permissions for the `gui_rpc_auth.cfg` file.

Thanks for all the help with this, I do appreciate it... I kinda feel like I wasted your time since it ended up being a perms issue.

**Comment by makeasnek** [comment]
Yay I'm glad we found a fix and thank you for debugging this with me. I'll publish a new version within the next hour or so that will detect issues connecting to BOINC and advise suggestions to fix them.

' On RPi1, somehow having the group owner lpadmin allowed FTM to access the file... I'm not going to dig into this one.'<-- This is probably because your username is in the lpadmin group.

**Comment by HeyMerlin** [comment]
> ' On RPi1, somehow having the group owner lpadmin allowed FTM to access the file... I'm not going to dig into this one.'<-- This is probably because your username is in the lpadmin group.

Just checked and yes that is the reason.
(hoping this comment does not re-open the issue)
