### ISSUE TITLE
Feature request: date/time stamps in logging statements

### ISSUE THREAD

**Issue by HeyMerlin** [makeasnek/FindTheMag2#13]
I'd like to request that adding timestamps to all log messages be considered.

Currently without date/timestamps it is hard to relate entries in the debug.log file to entries in the BOINC event log. Also when just looking at the debug.log file it is difficult to track changes over days.

It would also be useful if on startup the very first thing FTM did is log a startup entry which includes a separator along with date/time and the version number. 

I thing this would make parsing and monitoring the log much easier.

**Comment by makeasnek** [comment]
This is a feature that should definitely be added. Probably won't be done soon, but the next time I'm making significant changes this will get added in (there's some other fixes regarding url handling and code simplicity that should be done as well). I'll leave this open until then as a reminder.

**Comment by makeasnek** [comment]
I also know how to do branching in git, which I didn't before, which should enable a "testing" and "stable" branch instead of just immediately pushing everything to live production.

**Comment by makeasnek** [comment]
Fixed in latest release v 3.0
