### ISSUE TITLE
Feature request: local config file for site specific config

### ISSUE THREAD

**Issue by HeyMerlin** [makeasnek/FindTheMag2#16]
The issue I have with editing/modifying config.py is that I then have to deal with merging my custom settings anytime I download or pull the latest version from the repository. Instead of having users directly edit config.py, I propose treating that file as a "default settings" file, and then having the user create another file (ex. config-local.py) where all site specific customizations are put.
Main.py would then source the config.py file and then, if it is present, source config-local.py. This would allow the user to store their custom settings and not have merge issues whenever a new version of FTM is downloaded/pulled.

This does not stop the user from editing config.py if that is what they want to do. At the same time, if they just want the defaults they leave config.py and do not create config-local.py. When they want a custom setting they can copy the relevant setting out of config.py into config-local.py and change the value.

This will also make it easier if the project eventually gets and installer and installs to the standard locations, as the config-local.py could exist in the users home directory.

**Comment by makeasnek** [comment]
This is a great idea and will be implemented in the next release :).

**Comment by makeasnek** [comment]
Fixed in latest release v 3.0
