### ISSUE TITLE
Found unknown messagex: Project requested delay of 7 seconds

### ISSUE THREAD

**Issue by HeyMerlin** [makeasnek/FindTheMag2#18]
Is "messagex" correct? 

But the real reason for this issue... the "Project requested delay ..."

Looking at main.py, it looks like this message was removed the positive list due to projects sending this message out even when there is work, etc. However might I suggest adding the message to `ignore_phrases` so that the log entry is not continually generated and backoff is still returned as false.

**Comment by makeasnek** [comment]
This one is just in there for debugging purposes (though it should probably be logging.debug not logging.warning). The reason that particular message isn't ignored is that eventually I want to take that backoff value and actually add it into the backoff database. Right now, the message is not interpreted as requiring backoff, as the re-check interval is inherently greater than the backoff these messages _usually_ request so there's no urgent need to interpret it that way, but in a perfect world it would be. So it's basically in there as a todo note to self. I think BOINC also won't re-check a project even if requested if it's backed off for this reason, but I'm not positive on that.

BOINC issues all sorts of messages, which seem among many other things such as task status codes to be documented nowhere (so I could not write code to handle all possible messages), hence why we have this "unknown message" log function. Gradually, I hope to build up a database of all possible messages so I can handle them all. 

If it's filling up your logs, feel free to comment out that line entry :). I'm going to leave this issue open as a reminder to implement this change in the next major version which probably won't be coming out for a while. All the important messages have been found and accounted for, so you won't miss anything important by commenting it out.

**Comment by HeyMerlin** [comment]
That all sounds reasonable. If I come across more that fall under the default do you want new issues or added to this one?

**Comment by makeasnek** [comment]
If you could add onto this one, that would be great. I can only get a certain variety of messages on my machines, I know there's some I'll never see, so it's good to have extra eyes on them :)

**Comment by HeyMerlin** [comment]
Sounds good... Also, strings output of the boinc binary shows a ton of different messages. If it would be useful I could parse through the output and eliminate all the cruff leaving only the potential messages. They would have to be validated over time but it should give you a better idea of potential messages. I could attach the result to this issue.

**Comment by makeasnek** [comment]
That would be great :)

**Comment by HeyMerlin** [comment]
Here is my first pass at stripping out all of the error/log messages from the boinc-client binary. 
Notes:

- I have left a lot of strings in that in in printf format (or similar). Some of these could be ignored but I left them in case they are useful for pattern matching.
- I have not sorted or uniqued the file because in some cases the order of the messages show context. Example: the command line usage messages.
- I did remove many one worded "messages" or any messages that I felt could not be easily detected. Example "%s:%s" does not give you much to go on.


[boinc-strings.txt](https://github.com/makeasnek/FindTheMag2/files/11357429/boinc-strings.txt)

**Comment by makeasnek** [comment]
THIS IS AWESOME THANK YOU!!! I will add all those into the next major release

**Comment by makeasnek** [comment]
Note: I will also probably want to convert these lists of strings (or at least some portion of them depending on how they are matched) into sets for performance reasons.

**Comment by makeasnek** [comment]
Just a heads up I added this particular message to the ignore list since it's a very common one. The rest I'll deal with in the next major release

**Comment by HeyMerlin** [comment]
Sounds good and you are most welcome... glad to help. 

Not sure how you are planning on managing the strings, but you may want to consider adding them to a separate file that you read in from main. Better maintainability and you don't blow up main.py with all of this.

**Comment by makeasnek** [comment]
That's probably the best way to do it, I hadn't thought that far in terms of structure how to lay it all out.

**Comment by makeasnek** [comment]
Fixed in latest release v 3.0
