### ISSUE TITLE
Increase in % not correct.

### ISSUE THREAD

**Issue by sweede-se** [makeasnek/FindTheMag2#25]
The calculation of the increase in % is not correct.

`When you started using this tool, your average mag/hr was: 0.0036 now it is 0.0053 That's an increase of 0.49%! `

**Comment by HeyMerlin** [comment]
I have seen that too. Have not had the time to look at it though. At some point I'll gather examples from my instances running.

**Comment by makeasnek** [comment]
Closing since a recently pull request fixed this
