### ISSUE TITLE
Control Folding@Home

### ISSUE THREAD

**Issue by Dave247** [makeasnek/FindTheMag2#31]
I don't know how feasible this would be to even do, if it even can be done at all. Really the main thing I would want is some external thing that is aware of both BONIC and Folding@Home, and be able to balance them both accordingly, so there's no concern for them having to fight for resources.

AS F@H has its own crunching and control method though, tying to get compatibility with BONIC is always going to be a challenge. Though surely there is some external way you can control it, and hopefully even a solution using python?

**Comment by makeasnek** [comment]
Thank you for the suggestion however I have no plans to add support for Folding@home into this tool. If somebody were to write code for an "extension" platform for FTM, in theory, one could write "extensions" for Folding@home and any other incentivized distributed computing tool. If you're interested in doing that lmk.
