### ISSUE TITLE
Weight Control

### ISSUE THREAD

**Issue by Brewsmithy** [makeasnek/FindTheMag2#32]
Not really an issue, just a bit of confusion that could use some tuning. My setup was boinc on Windows 10, using BOINC/stats as a manager. I had set weights for different projects before starting FTM3. 

It was not clear in the install instructions (readme.me) about how to prepare before starting FTM3. Was I, as a user, supposed to set my individual projects to 1 weight before starting? I had 4 projects set at 100, the rest at 1 prior to starting. I did not see a change in weight when FTM3 started. 

Instead of setting the weights at BOINC/stats, I disconnected the manager, went to the individual projects, set them all to 1, and continued running FTM3. 

Does FTM3 control weight on individual projects? Does being connected to BOINC/stats interfere with FTM3's control of weights? Do I wait for FTM3 to adjust weights going forward for the increased earnings?

Thank you for your great work, I really do appreciate you doing this!

Cheers

**Comment by makeasnek** [comment]
Thank you for the feedback!

So there are two ways to use FTM:

1. Just have FTM read your stats and suggest weights. If you do this, nothing changes until you take those weights and plug them into either your BOINC account manager or individual project sites. Then, BOINC will adjust your crunching to match those weights.

2. Have FTM directly control boinc. If you do this, FTM will over-ride whatever weight settings come from your account manager and project websites. All whitelisted projects (unless you excluded them in your config) you are attached to get a minimum weight of 1 for continuous benchmarking. After that, it assigns weight based on your preferred vs mining projects. If you have no preferred projects, it will assign all weight to the most profitable project and any other project which is within 10% of that project's profitability.

Worth noting that you can do option 1 for free forver while option 2 requires crunching for dev (minimum 1% of crunching time) after approx 1000 hours or setting up a sidestake.

Let me know if that's clearer. I know the readme is a bit confusing, but I don't know how/where to make it easier. It's a power tool with a bunch of things to configure.
