### ISSUE TITLE
Suggestion for readme 

### ISSUE THREAD

**Issue by ljez** [makeasnek/FindTheMag2#4]
Hi!

Could you please explain in the readme what a host group is and what is its purpose, in general and for the use of FindTheMag2?  I am contributing to Arikado pool, where there is no such concept, and I do not understand whether the lack of host groups is a limitation.

Also, I do not understand from the readme or running the tool just for stats if the stats it provides are provided for all the hosts together or separate, per host.

Thanks!

**Comment by makeasnek** [comment]
In Arikado you can assign different project weights to individual hosts, I'm not sure if they support host _groups_ or not, but if not then there's no issue. The stats shown by the tool are specific to the machine you are running it on.
