### ISSUE TITLE
Gracefully closing with no Gridcoin install causes syntax error

### ISSUE THREAD

**Issue by Dave247** [makeasnek/FindTheMag2#41]
A strange one, that I only happened to stumble upon when I was testing for my other ticket #40. It requires you to gracefully terminate the script without a valid Gridcoin data directory, which is an extremely specific set of steps that no one is likely to ever come across in the typical use of the script, so you could consider this to be the lowest possible priority to fix. This happens on all python versions 3.8 to 3.12, and in both [3.0 release](https://github.com/makeasnek/FindTheMag2/releases/tag/3.0) and the latest commit at the time of posting 8772d49a6ca28509c473eda9c38ac205877ad89b

```
C:\Users\david\Desktop\FindTheMag2 new>python main.py
Gridcoin data dir does not appear to exist. If you have it in a non-standard location, please edit config.py so we know where to look
Press enter to continue or CTRL+C to quitProgram exiting gracefully. Please be patient this may take a few minutes
Traceback (most recent call last):
  File "C:\Users\david\Desktop\FindTheMag2 new\main.py", line 4212, in <module>
    input("Press enter to continue or CTRL+C to quit")
  File "C:\Users\david\Desktop\FindTheMag2 new\main.py", line 567, in safe_exit
    if os.path.exists(override_dest_path):
                      ^^^^^^^^^^^^^^^^^^
NameError: name 'override_dest_path' is not defined
```

**Comment by makeasnek** [comment]
Thank you for the bug report, this is a definetely a bug, that variable should always exist even if you don't have a valid Gridcoin folder. I'll get this fixed in the next release.
