### ISSUE TITLE
Ignored projects aren't actually ignored

### ISSUE THREAD

**Issue by jwaggy** [makeasnek/FindTheMag2#45]
I had assumed that setting a project as ignored would set it to "won't get new tasks" permanently, instead it has it's weight set to zero and still updates with the rest of the projects. In my case this ended up reducing my mag until I caught on.

**Comment by makeasnek** [comment]
Thank you for the bug report! I will look into this and get it fixed in the next release.

**Comment by makeasnek** [comment]
Fixed in the latest release
