### ISSUE TITLE
Windows install, won't run, "No module named 'xmltodict'"

### ISSUE THREAD

**Issue by davisbeeman** [makeasnek/FindTheMag2#46]
Installed per instructions, xmltodict does install, but when I run the program I get:

`PS D:\BOINC\Find\FindTheMag2-3.2> python main.py
D:\BOINC\Find\FindTheMag2-3.2\main.py:4968: SyntaxWarning: invalid escape sequence '\|'
  """
Error loading some required modules. Make sure you have installed the modules in requirements.txt as documented in the README
No module named 'xmltodict'
PS D:\BOINC\Find\FindTheMag2-3.2>`

Proof of xmltodict install:

`PS D:\BOINC\Find\FindTheMag2-3.2> pip install -r requirements.txt
Requirement already satisfied: certifi in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 1)) (2023.7.22)
Requirement already satisfied: charset-normalizer in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: DateTime in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 3)) (5.4)
Requirement already satisfied: exceptiongroup in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 4)) (1.2.0)
Requirement already satisfied: idna in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 5)) (3.4)
Requirement already satisfied: iniconfig in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 6)) (2.0.0)
Requirement already satisfied: packaging in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 7)) (23.2)
Requirement already satisfied: pluggy in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 8)) (1.4.0)
Requirement already satisfied: pytest in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 9)) (8.0.2)
Requirement already satisfied: pytz in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 10)) (2024.1)
Requirement already satisfied: requests in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 11)) (2.31.0)
Requirement already satisfied: tomli in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 12)) (2.0.1)
Requirement already satisfied: typing in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 13)) (3.7.4.3)
Requirement already satisfied: urllib3 in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 14)) (2.2.1)
Requirement already satisfied: xmltodict in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 15)) (0.13.0)
Requirement already satisfied: zope.interface in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 16)) (6.2)
Requirement already satisfied: nest-asyncio in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 17)) (1.6.0)
Requirement already satisfied: colorama in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from pytest->-r requirements.txt (line 9)) (0.4.6)
Requirement already satisfied: setuptools in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from zope.interface->-r requirements.txt (line 16)) (69.1.0)`

**Comment by makeasnek** [comment]
Thank you for the bug report! Can you output the results of `python --version` and `pip --version`

**Comment by davisbeeman** [comment]
Still happening, with latest update

PS C:\Users\tempe\Downloads\FindTheMag2-3.3\FindTheMag2-3.3> python --version
Python 3.12.2
PS C:\Users\tempe\Downloads\FindTheMag2-3.3\FindTheMag2-3.3> pip --version
pip 24.0 from C:\Users\tempe\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip (python 3.12)
PS C:\Users\tempe\Downloads\FindTheMag2-3.3\FindTheMag2-3.3>

**Comment by makeasnek** [comment]
What happens if you run `python -m pip install -r requirements.txt`, does that fix it?

**Comment by davisbeeman** [comment]
This is after I run that.   You can see it in the other issue I opened (wasn't sure you would see this one, as it was closed, so I opened another)

**Comment by makeasnek** [comment]
That one uses the `pip install` line, try with the `python -m pip install -r requirements.txt` format

**Comment by davisbeeman** [comment]
That did seem to fix that issue, now I get 

`D:\BOINC\Find\FindTheMag2-3.3\main.py:4967: SyntaxWarning: invalid escape sequence '\|'
  """
BOINC data dir does not appear to exist. If you have it in a non-standard location, please edit config.py so we know where to look
Press enter to exit`

I do have it in a non-standard location, but looking through the config.py file, I do not see any variable for location.   Am I missing something?

**Comment by makeasnek** [comment]
Glad that fixed it :). 

Edit the variable BOINC_DATA_DIR in config.py (or user_config.py if you have one, which is suggested)
