### ISSUE TITLE
FTM doesn't connect to wallet properly after upgrade to 5.4.6.0

### ISSUE THREAD

**Issue by jwaggy** [makeasnek/FindTheMag2#48]
The error shown is "Error communicating with Gridcoin wallet! 'Contract Contents'".

**Comment by makeasnek** [comment]
Thank you for the bug report! Can you please send a copy of your debug.log to makeasnek{at}gmail.com?

Given the urgency of this issue, I will get this fixed in the next couple days

**Comment by jwaggy** [comment]
I just sent it to you.

**Comment by makeasnek** [comment]
Thank you! Fixed in the latest release
