### ISSUE TITLE
xmltodict issue with windows install

### ISSUE THREAD

**Issue by davisbeeman** [makeasnek/FindTheMag2#49]
As previous issue, tried with newest update, same issue.   Included requested python and pip versions

`PS C:\Users\tempe\Downloads\FindTheMag2-3.3\FindTheMag2-3.3> pip install -r requirements.txt
Requirement already satisfied: certifi in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 1)) (2023.7.22)
Requirement already satisfied: charset-normalizer in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: DateTime in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 3)) (5.4)
Requirement already satisfied: exceptiongroup in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 4)) (1.2.0)
Requirement already satisfied: idna in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 5)) (3.4)
Requirement already satisfied: iniconfig in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 6)) (2.0.0)
Requirement already satisfied: packaging in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 7)) (23.2)
Requirement already satisfied: pluggy in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 8)) (1.4.0)
Requirement already satisfied: pytest in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 9)) (8.0.2)
Requirement already satisfied: pytz in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 10)) (2024.1)
Requirement already satisfied: requests in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 11)) (2.31.0)
Requirement already satisfied: tomli in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 12)) (2.0.1)
Requirement already satisfied: typing in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 13)) (3.7.4.3)
Requirement already satisfied: urllib3 in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 14)) (2.2.1)
Requirement already satisfied: xmltodict in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 15)) (0.13.0)
Requirement already satisfied: zope.interface in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 16)) (6.2)
Requirement already satisfied: nest-asyncio in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 17)) (1.6.0)
Requirement already satisfied: colorama in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from pytest->-r requirements.txt (line 9)) (0.4.6)
Requirement already satisfied: setuptools in c:\users\tempe\appdata\local\programs\python\python312\lib\site-packages (from zope.interface->-r requirements.txt (line 16)) (69.1.0)

PS C:\Users\tempe\Downloads\FindTheMag2-3.3\FindTheMag2-3.3> python main.py
C:\Users\tempe\Downloads\FindTheMag2-3.3\FindTheMag2-3.3\main.py:4967: SyntaxWarning: invalid escape sequence '\|'
  """
Error loading some required modules. Make sure you have installed the modules in requirements.txt as documented in the README
No module named 'xmltodict'

PS C:\Users\tempe\Downloads\FindTheMag2-3.3\FindTheMag2-3.3> python --version
Python 3.12.2

PS C:\Users\tempe\Downloads\FindTheMag2-3.3\FindTheMag2-3.3> pip --version
pip 24.0 from C:\Users\tempe\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip (python 3.12)
PS C:\Users\tempe\Downloads\FindTheMag2-3.3\FindTheMag2-3.3>`

**Comment by makeasnek** [comment]
Resolved in another issue thread
