### ISSUE TITLE
Can't install on macos

### ISSUE THREAD

**Issue by hassos246** [makeasnek/FindTheMag2#52]
FindTheMag2 % pip3 install -r requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-brew-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-brew packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
WARNING: Skipping /opt/homebrew/lib/python3.12/site-packages/charset_normalizer-3.3.2.dist-info due to invalid metadata entry 'name'

**Comment by makeasnek** [comment]
This is due to how your system is setup, not a problem to fix/change with FTM. I would suggest using a venv as it suggests, but installing packages sitewide is usually safe as well.
