### ISSUE TITLE
NoneType object has no attribute upper

### ISSUE THREAD

**Issue by jwaggy** [makeasnek/FindTheMag2#53]
I closed ftm2 and restarted it and I get this error. It also doesn't find the sidestaking information.

[2024-06-23 11:16:49,139] ERROR [root.print_and_log:4518] Error communicating with Gridcoin wallet! 'NoneType' object has no attribute 'upper'

**Comment by makeasnek** [comment]
My guess is that your Gridcoin wallet isn't open or its RPC port isnt' open. Is FTM not prompting you to allow it to communicate with the wallet? Please make sure you are running the latest version of FTM, set the loglevel to DEBUG, and then send the log to makeasnek at gmail.com and I'll look into it. Thanks!

**Comment by jwaggy** [comment]
I restarted the Gridcoin wallet and it started magically working again. Sorry for the bother.

**Comment by makeasnek** [comment]
No worries glad its working again thanks for using FTM :)
