### ISSUE TITLE
GRCPRICE not being written to DB

### ISSUE THREAD

**Issue by Jericon** [makeasnek/FindTheMag2#54]
After my first run of the program, subsequent runs fail with the following error:

`Traceback (most recent call last):
  File "/home/grcuser/FindTheMag2/main.py", line 5042, in <module>
    boinc_loop(False, rpc_client)
  File "/home/grcuser/FindTheMag2/main.py", line 4017, in boinc_loop
    grc_price = DATABASE["GRCPRICE"]
KeyError: 'GRCPRICE'`

It seems that in the stats.json file, the GRCPRICELASTCHECKED is being written, but the GRCPRICE is not.  To resolve the issue, GRCPRICELASTCHECKED needs to be removed and then the client works fine.  I believe this may be due to the price check failing to get a value, or the program failing to write a "0.000" GRCPRICE value to the "database".

**Comment by Jericon** [comment]
I found a couple of things that can improve the behavior if there is no value in the database.  Also, a logic fix that will prevent the LASTCHECKED value from being written if a price is not retrieved.  

I am making a PR to fix those both now.  However, potentially some error messages or something if a value cannot be obtained is warranted.

**Comment by Jericon** [comment]
This PR will fix the issue by moving the update of the LASTCHECKED value to only be updated if a new price is attained.  Likewise, it will run the block to try to get a new price if there is no value in the DB for GRCPRICE but there is a LASTUPDATED value.

https://github.com/makeasnek/FindTheMag2/pull/55

**Comment by makeasnek** [comment]
Fixed by https://github.com/makeasnek/FindTheMag2/pull/55
