### ISSUE TITLE
Crashes when attempting to control BOINC.

### ISSUE THREAD

**Issue by RubyKitsune** [makeasnek/FindTheMag2#7]
Relevant stacktrace below, topic as above.

```
Starting control of BOINC...
Traceback (most recent call last):
  File "D:\Tools\FindTheMag2-main\main.py", line 2587, in <module>
    shutil.copy(override_path,override_dest_path)
  File "C:\Users\sythi\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\sythi\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ProgramData\\BOINC\\global_prefs_override.xml'
Press any key to continue . . .
```

**Comment by RubyKitsune** [comment]
Quick update, the file didn't exist, and it was a PEBKAC error on my behalf, it was using web preferences. UX could use some work, maybe this error needs catching in the script.

FWIW I switched from BAM to this, tbh.

**Comment by makeasnek** [comment]
Thank you for your bug report! I'll add some better error catching and reporting here, what was the solution in the end to stop this error from happening?

**Comment by RubyKitsune** [comment]
> Thank you for your bug report! I'll add some better error catching and reporting here, what was the solution in the end to stop this error from happening?

Literally, just manually override the existing web config with a local one. It was a simple fix once I realised it was relying on that particular file.

**Comment by makeasnek** [comment]
Gotcha. I have updated it now so it will gracefully ignore the file if it doesn't exist. Thank you for bringing this to my attention, let me know if you hit any other snags!
