### ISSUE TITLE
Won't get new tasks - Windows Desktop PC

### ISSUE THREAD

**Issue by JonathanEdMoore** [makeasnek/FindTheMag2#9]
Every project is showing "Won't get new tasks" on my PC. This started happening once World Community Grid starting having issues.

**Comment by makeasnek** [comment]
Thank you for the bug report! Can you give me a list of the project weights shown in the output? Are you actually still receiving and crunching tasks or no? Were any projects added/removed recently? I noticed a similar issue on one of my machines where the "highest priority project" was removed from BOINC but the script didn't know so it kept leaving that one on "allow new tasks" in BOINC but of course that command did nothing as BOINC didn't know about the project. If that's the situation, turning the script off, deleting the stats.json file, and then starting the script again will reset the script's list of projects, but I should add a way to detect and automate this.

**Comment by makeasnek** [comment]
If that doesn't work, please do the following:

1. Turn off script
2. Edit config.py so log level is DEBUG. Delete existing debug.log.
3. Run script until issue occurs
4. Send me debug.log (makeasnek at gmail.com)

**Comment by makeasnek** [comment]
* Also please send me a list of projects which are currently attached in BOINC

**Comment by makeasnek** [comment]
Alternatively, if your script was already set to debug mode for the log, then just send me the pre-existing log.

**Comment by JonathanEdMoore** [comment]
I'm running `DEBUG` right now. I'll send you the log later tonight. However, looking at the logs makes me think that it's not fetching new tasks because it doesn't think any of my non-preferred projects are profitable. I did adjust my `local_kwh` upwards, so that might be the reason. But, I have the same settings on my Mac computer and it's still fetching tasks.

I'll send the logs over tonight so you can also take a look.

List of projects attached to BOINC:

- Amicable Numbers
- Asteroids@home
- Einstein@Home
- latinsquares
- Milkyway@Home
- NFS@Home
- NumberFields@home
- Rosetta@home
- SiDock@home
- Universe@Home
- yoyo@home

**Comment by JonathanEdMoore** [comment]
I'm not sure what "NNT" is referring to. I can say that it's not fetching tasks on occasion.

I had `only_BOINC_if_profitable` set to `True`. I did a quick test by setting it to `False` and that got it to fetch new tasks.

What's strange is that my config.py on my PC is identical to my config.py on my Mac. But my Mac is fetching tasks.

Prior to changing my `config.py` file, I sent it to your email.

**Comment by makeasnek** [comment]
NNT = setting a project to "no new tasks". If only_BOINC_if_profitable was set to True, then it sounds like the program is working as expected, it wasn't fetching new tasks because it determined all projects are unprofitable. Let me know if the issue recurs and send me a new debug log if so :).

**Comment by makeasnek** [comment]
Just looked at the log, this was definitely the source of the issue: "No projects currently profitable and no benchmarking required, sleeping for 1 hour and killing all non-started tasks"
